name: archflow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  flutter_riverpod: ^3.2.0
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  markdown_widget: ^2.3.2+8
  uuid: ^4.5.2
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/archflow.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/archflow.png"
  remove_alpha_ios: true
